# إعدادات الموقع الأساسية
title: "علي عبد الأمير مهدي الجبوري"
description: "مدونة شخصية للأبحاث، ومسودات الأسس المعرفية للفلسفة الفقهية والقواعد الهيكلية."
author: "علي عبد الأمير مهدي الجبوري"

# إعدادات التصميم واللغة
lang: "ar"
direction: "rtl"
theme: jekyll-theme-minimal

# روابط القائمة الجانبية (يمكننا إضافة المزيد لاحقاً)
email: "your-email@example.com"
